### ISSUE TITLE
Don't parse beatmaps.

### ISSUE THREAD

**Issue by ssCherry** [LW2904/maniac#19]
![default](https://user-images.githubusercontent.com/42537021/45593232-46d83500-b98a-11e8-937e-c30c5c8cb58d.png)

**Comment by LW2904** [comment]
The error you're getting indicates that `parse_beatmap` failed, which could either be because it received invalid arguments (meaning that an earlier step failed but wasn't detected) or because it failed to open the beatmap file. I consider the latter to be more likely.

This might be an issue with permissions, you could try to run `maniac` from an admin shell (ergo from a CMD.exe that was started with admin rights).

Could you run a debug build and let me know what debug messages/errors you see?
