### ISSUE TITLE
Map detection issue

### ISSUE THREAD

**Issue by Sensest** [LW2904/maniac#38]
Hey, so everything seems to be working fine so far, however some maps seem to be detected as the same song but from another mapper, don't really know how to explain it so I'll list some examples of this happening, both maps tend to contain letters in the title that could be interpreted as the other so I guess that's the problem.

Both maps from Mania:
"I-Chroma" from Lude and "Made in Love-Chroma" from the same mapper:
https://osu.ppy.sh/beatmapsets/738673#mania/1558923
https://osu.ppy.sh/beatmapsets/831569#mania/2046467

From STD to Mania:
"Shiwa-Hanatan" from Ami's mapset (STD) and from puxtu's mapset (Mania)
https://osu.ppy.sh/beatmapsets/130704#osu/329967
https://osu.ppy.sh/beatmapsets/201333#mania/476759

And here's a weird instance in which they both share only a really small part of the name:
"escape-XX:me" and "Fascination MAXX"
https://osu.ppy.sh/beatmapsets/882486#mania/1845028
https://osu.ppy.sh/beatmapsets/409152#mania/927196

I know there's the option to manually input the path to the beatmap, but this could be labelled as bug anyways.

**Comment by LW2904** [comment]
Yeah, that's definitely a bug. The map finding algorithm is really stupid so this was bound to happen at some point.

Thanks for the links and the report, I'll look into implementing something more robust that doesn't fail in these cases.

**Comment by LW2904** [comment]
Alright so the commit I just pushed should fix the issue with similar names being confused for each other. I tested the first and third cases you presented and both now work as you'd expect.

The second case you linked is special since the folder names are exactly the same, barring the map ID. `maniac` attempts to find the currently played beatmap by fetching the title of the game window and first comparing that to the folder names in `osu!/Songs`. Once it has found the "best" folder it goes on to compare the title to the files in that folder. In this case, both folders get the same score (since the beatmap ID is not included in the window title) and the cheat just defaults to the first folder it found when two folders have the same score.

I divided the map finding process into these two stages since the alternative is iterating over all files in all folders which is very inefficient and could take more time than we have (only ~3s) until the first hitpoint is due. I'll have to do some thinking on this.

**Comment by LW2904** [comment]
There's also apparently still cases where it correctly finds the folder but selects the wrong file (in most cases it's not even a `.osu` file, which shouldn't even be possible), see #42.

I'm playing with some stuff that might eliminate this whole issue entirely, should have a better idea of how viable that is by tomorrow.

**Comment by LW2904** [comment]
Quick update since it's been a couple of days already. There's three major issues with the map detection at the moment (as far as I am aware) and they are

- folder detection (fails to find folders which only differ in their unique id, what @Sensest reported originally)
- file detection (since the window title and filename formats do not match perfectly, sometimes other files, like `${title}.mp3` get a better score, what @ari4431 reported recently in #42 )
- inflexibility in regards to the osu! path (the osu! default path is baked into the executable, can only be changed by recompiling, #15 )

I'm still playing around with a solution that should eliminate all these issues in one fell swoop while being significantly faster and simpler. I can't get it to work reliably yet, and it'll probably remain Windows-only but there's hope!

**Comment by LW2904** [comment]
It's been almost a month and I'm happy to say that all issues noted in my previous comment have now been solved. Since I somehow completely rewrote maniac along the way there are still some things to do (I didn't port over humanization yet, for example) but it's already usable and reasonably stable.

Expect a new release under a 1.x.x tag to come in the following days.
