### ISSUE TITLE
Double delay if pressed 

### ISSUE THREAD

**Issue by Hide-User** [LW2904/maniac#40]
Hello I propose to implement this option if possible that if a key is pressed this increases the offset temporarily as long as the key is pressed 20 -> 40 this would make the humanization a little more realistic and have X200 combo sometimes in the map

**Comment by LW2904** [comment]
So what you're saying is: once any key is pressed the offset for _all_ other keys should be increased for some set amount of time? Would this stack? (Let's call this option one.)

Or are you saying that the _user_ should be able to press a key in order to double the delay? (Option two.)

A way I could see something like option one being implemented: Every time any key is pressed the offset increases by some small value, say 2. Every 2-5 seconds or something this offset would decrease by some value, say 8, until it hits the original offset. The decrease could even be proportional to the "gained" offset.

This would lead to naturally higher delays in very dense areas of the map and return to the regular offset once things are more chill.

**Comment by Hide-User** [comment]
Exactly that would make it a little more human because a human makes 200 when it's harder or just by choke.

**Comment by Hide-User** [comment]
it also means that we do not have a fixed UR as in this screenshot
![screenshot126](https://user-images.githubusercontent.com/62671486/80377680-e3b7bf80-889b-11ea-833a-9d1390252202.jpg)

**Comment by LW2904** [comment]
Just created a "Humanization" project, I like this suggestion but I think it deserves some more thought. I'll add issues/notes as I think of stuff, feel free to create issues with more enhancements in regards to humanization and add them to the project.

**Comment by LW2904** [comment]
I implemented this suggestion in v0.7.0-alpha, which I marked as an alpha release since I didn't test it very exhaustively.

You can try out the new feature by running maniac with the `-x` or `--exp-humanization` option.
```bash
$ maniac.exe -x 2:500	# offset increases by 2ms on every keypress and decays by
                        # 2*4ms every 500ms

$ maniac.exe --exp-humanization 2:500 # this is equivalent to the above
```

I'd really appreciate it if you could play around with the values a bit, let me know what works best for you.

**Comment by Sensest** [comment]
I just tried it and couldn't notice anything... Started from low values like 1:1000 and went to the point of trying 50:10000 just to check if it was changing anything at all, and for me at least, it isn't changing the offset. Tried with and without the other parameters and it didn't seem to work either.
Btw, maybe you could add a value from which the offset doesn't drop from?, since the "regen" will set the offset really low in the slow parts.

**Comment by LW2904** [comment]
My bad, I deleted a couple of debug logs right before I pushed the new release and accidentally deleted the most important statement (which actually adds the calculated delay to the actions).

This should be fixed with v0.7.0-beta. I'm not particularly happy with the way this works at the moment, but maybe I just haven't found the right settings yet.

**Comment by Hide-User** [comment]
Yes it does not work very well because once late maniac does not catch up and dies.

**Comment by Sensest** [comment]
Played around the settings for an hour and yeah, It either dies or goes just like without the calculated delay... low regen and delta values tend to miss randomly and it's not far from the normal humanization, and on the other side, high regen and delta values tend to just die in dense parts of the map. It's a really good idea for humanization but it seems complicated to pull off

**Comment by LW2904** [comment]
I liked the idea, but it looks like it's not really viable in practice. Closing this now, please don't hesitate to create a new issue if you have another idea.
