### ISSUE TITLE
Maniac unhandled exception: failed reading memory

### ISSUE THREAD

**Issue by Hide-User** [LW2904/maniac#48]
![Capture](https://user-images.githubusercontent.com/62671486/83584169-97b90400-a546-11ea-828f-aa1f5e7d2d0d.PNG)

**Comment by LW2904** [comment]
Yeah, it mysteriously dies occasionally -- I'm looking into it at the moment. This is the reason that this is a release candidate (1.0.0-__rc__6) and not a full release.

**Comment by LW2904** [comment]
Forgot to ask: does restarting fix the issue, and do you notice it crashing on a specific bestmap or at a specific time?

**Comment by Hide-User** [comment]
No after Restart is same but i have a new message 
![Capture](https://user-images.githubusercontent.com/62671486/83584945-dcde3580-a548-11ea-8622-9e61a7810332.PNG)

**Comment by LW2904** [comment]
Could you try downloading a debug build (`maniac-dbg.exe`) and post results? And please make sure the beatmap you're playing was made for mania, non-mania maps aren't supported yet.

Thanks for the info so far and sorry for the inconvenience!

**Comment by Hide-User** [comment]
Hi i tried with differents beatmaps and don't work.
![Capture](https://user-images.githubusercontent.com/62671486/83608780-a1aa2980-a57d-11ea-9a92-e17fe508a931.PNG)

**Comment by LW2904** [comment]
Hey there, I just pushed some changes that should make the reported errors more informative.

As a potential workaround for your issue, please try the following steps:

1. Start osu, start playing any beatmap for a couple of seconds and then either exit or pause.
2. Start maniac, it should now work as expected.

This is due to osu using a just-in-time compiler -- the code that handles beatmap playing (which maniac needs to function) simply isn't there until the first time you went in a map.

**Comment by Hide-User** [comment]
![image](https://user-images.githubusercontent.com/62671486/83704002-40339a80-a611-11ea-8469-8b60a7d3d81b.png)
 it still doesn't work and I did what you said

**Comment by LW2904** [comment]
Looks like the issue you have now is already tracked in #49, I'll add a comment there once I have a fix.

Closing this since the original issue isn't really something I can fix from my end; I added a note to the usage section with the above workaround.

**Comment by Hide-User** [comment]
Hi @LW2904  the last version solved my problem. :3
