### ISSUE TITLE
"Sticky" keys when starting a new map

### ISSUE THREAD

**Issue by LW2904** [LW2904/maniac#60]
After playing through a map with maniac some keys are still being "held down" in the next map, messing up the first couple of hits.

**Comment by angrybird9797** [comment]
I've seen this issue on other mania hacks too. It seems to be a common problem. My bet is it's due to the slider notes. When playing slider notes, the app is doing a "key_down" until the slider is over and then does a "key_up". So when a slider note(key_down) isn't over yet and user back to menu/restarting the map, the key_down state is still present that causes first note that using the same key to be messed up. User can fix this by pressing all the keys used for the map. Like for example 4k map, by pressing DFJK keys before first note plays so any key_down will be released up. In the code, maybe try to implement release keys when restarting/playing a new map. Wish could explain it better but my English isn't that good.

**Comment by LW2904** [comment]
Yeah, sliders are almost certainly the issue and the workaround you suggested works: that's how I used to do it pre-rewrite. It's a bit of a hacky solution though and I kinda hoped I'd come up with a better way to do it, which is why I didn't port it over initially.

It's a really quick fix though so I'll just add it alongside a `TODO` or something.

**Comment by LW2904** [comment]
Fixed in #65 , I'd appreciate it if you could test the [preview build](https://github.com/LW2904/maniac/actions/runs/164738118) before I create a new release for this.

**Comment by ANB1997** [comment]
It does fix the sticky keys very nice. However, I tried to play without cheat and pause the game in the middle of a slider note and launch the cheat, it didn't continue to play the slider note therefore causing a slider break. But I think it's an irrelevant bug that can be easily avoided by running the cheat from the beginning.

**Comment by LW2904** [comment]
That's good to hear, thanks for confirming.

Never thought of that, and honestly it's probably not worth the effort to fix. If it's something you want to see fixed, feel free to create an issue and I'll eventually get to it.
